app_jobForum/urls.py
from django.conf.urls import url
from .views import index, add_forum, comments, add_comment

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-forum/$', add_forum, name='add_forum'),
	url(r'^add-comment/(?P<id>.*)/$', add_comment, name='add_comment'),
	url(r'^comments/(?P<id>.*)/$', comments, name='comments'),
]

app_mainAndLogin/urls.py
from django.conf.urls import url
from .views import index, add_perusahaan
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_perusahaan/', add_perusahaan, name='add_perusahaan'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_respondToMain/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

ssco/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import app_jobForum.urls as jobForum
import app_mainAndLogin.urls as mainAndLogin
import app_profile.urls as profile
import app_respondToMain.urls as respond

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^job-forum/', include(jobForum,namespace='jobForum')),
	url(r'^main/', include(mainAndLogin,namespace='mainAndLogin')),
	url(r'^profile/', include(profile,namespace='profile')),
	url(r'^respond/', include(respond,namespace='respond')),
	url(r'^$', RedirectView.as_view(url='/main/',permanent='true'), name='index'),
]

app_jobForum/models.py
from django.db import models

class Forum(models.Model):
	forum = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)
   
	class Meta:
		ordering = ['-created_date']

class Comments(models.Model):
	forum_id = models.ForeignKey(Forum)
	name = models.TextField()
	comment_content = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	# updated_at = models.DateTimeField(auto_now=True)

app_mainAndLogin/models.py
from django.db import models

# Create your models here.
class Perusahaan(models.Model):
	comp_id = models.CharField(max_length=400)
	nama = models.CharField(max_length=400)
	deskripsi = models.CharField(max_length=250)
	weburl = models.CharField(max_length=250)
	specialties = models.CharField(max_length=250)
	logoUrl = models.CharField(max_length=250)
	tipe = models.CharField(max_length=250)

app_profile/models.py
from django.db import models

# # Create your models here.
# class Perusahaan(models.Model):
# 	comp_id = models.CharField(max_length=400)
# 	nama = models.CharField(max_length=400)
# 	deskripsi = models.CharField(max_length=250)
# 	weburl = models.CharField(max_length=250)
# 	specialties = models.CharField(max_length=250)
# 	logoUrl = models.CharField(max_length=250)
# 	tipe = models.CharField(max_length=250)

app_respondToMain/models.py
from django.db import models

# Create your models here.

app_jobForum/forms.py
from django import forms

class Add_New_Forum_Form(forms.Form):
    forum_attrs = {
        'class': 'form-control',
        'placeholder':'Please fill out your new secret villain job',
        'rows':10,
        'cols':100
    }

    forum = forms.CharField(label='',widget=forms.Textarea(attrs=forum_attrs), required=True)

class Add_New_Comment(forms.Form):
    comment_attrs = {
        'class': 'form-control',
        'placeholder':'Please fill out your new secret villain job',
        'rows':10,
        'cols':100
    }

    name_attrs = {
        'placeholder':'Please fill out your name',
        'rows':1,
        'cols':100
    }

    name =  forms.CharField(label='',widget=forms.Textarea(attrs=name_attrs), required=True)
    comment = forms.CharField(label='',widget=forms.Textarea(attrs=comment_attrs), required=True)

app_jobForum/views.py
from django.shortcuts import render
from django.template.loader import get_template
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Add_New_Forum_Form, Add_New_Comment
from .models import Forum, Comments

response={}
def index(request):
    response['base'] = get_template('base.html')
    response['forum_form'] = Add_New_Forum_Form
    response['all_forum'] = Forum.objects.all()
    html = 'job_forum.html'
    return render(request, html, response)

def add_forum(request):
    form = Add_New_Forum_Form(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        response['new_forum'] = request.POST['forum']
        forum = Forum(forum=response['new_forum'])
        forum.save() 
        return HttpResponseRedirect('/job-forum/')
    else:
    	return HttpResponseRedirect('/job-forum/')

def paginate_page(page, data_list):
    paginator = Paginator(data_list, 5) # pragma: no cover

    try: # pragma: no cover
        data = paginator.page(page)
    except PageNotAnInteger: # pragma: no cover
        data = paginator.page(1)
    except EmptyPage: # pragma: no cover
        data = paginator.page(paginator.num_pages)

    index = data.number - 1 # pragma: no cover

    max_index = len(paginator.page_range) # pragma: no cover

    start_index = index if index >= 5 else 0 # pragma: no cover
    end_index = 5 if index < max_index - 5 else max_index # pragma: no cover

    page_range = list(paginator.page_range)[start_index:end_index] # pragma: no cover
    paginate_data = {'data':data, 'page_range':page_range} # pragma: no cover
    return paginate_data

def get_comment_by_forum_id(id):
    return Comments.objects.filter(forum_id_id=id)

def get_forum_by_forum_id(id):
    return Forum.objects.get(pk=id)

def comments(request, id):
    html = 'comments.html'
    response['base'] = get_template('base.html')
    response['id'] = id
        
    response['forum'] = get_forum_by_forum_id(id)

    response['all_comments'] = get_comment_by_forum_id(id)

    response['comment_form'] = Add_New_Comment
    # print(id)
    # print (Comments.objects.all())
    # print(response['all_comments'])

    return render(request, html, response)

    # obj_forum = get_forum_by_forum_id(id)
    # response['all_comment'] = get_comment_by_forum_id(id)

    # return render(request, html, response)

def add_comment(request, id):
    form = Add_New_Comment(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        response['new_comment'] = request.POST['comment']
        response['new_name'] = request.POST['name']
        comment = Comments(comment_content=response['new_comment'], forum_id_id=id, name=response['new_name'])
        comment.save() 
        return HttpResponseRedirect('/job-forum/comments/' + id)
    else:
    	return HttpResponseRedirect('/job-forum/comments/' + id)

app_mainAndLogin/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.template.loader import get_template
from app_mainAndLogin.models import Perusahaan 
from app_jobForum.models import Forum
from django.views.decorators.csrf import csrf_exempt
import json

response={}
def index(request):
	response['base'] = get_template('base.html')
	response['all_forum'] = Forum.objects.all()
	html = 'profile.html'
	return render(request, 'main.html', response)
    

def add_perusahaan(request):
	if request.method == 'POST':
		comp_id = request.POST['data[id]']
		name = request.POST['data[name]']
		desc = request.POST['data[description]']
		tipe = request.POST['data[companyType][name]']
		url = request.POST['data[websiteUrl]']
		spec = request.POST['data[specialties][values]']
		logo = request.POST['data[squareLogoUrl]']
		listResponse = {'id':id}
		newperusahaan = Perusahaan.create(comp_id=comp_id, nama=name, deskripsi=desc, tipe=tipe, url=weburl, spec=specialties, logo=logoUrl)
		return JsonResponse(listResponse)
	return HttpResponse

app_profile/views.py
from django.shortcuts import render
from django.template.loader import get_template
from app_mainAndLogin.models import Perusahaan 

response={}
def index(request):
	response['user'] = Perusahaan.objects.all().first()
	response['base'] = get_template('base.html')
	return render(request, 'profile.html', response)

app_respondToMain/views.py
from django.shortcuts import render
from django.template.loader import get_template

response={}
def index(request):
    response['base'] = get_template('base.html')
    return render(request, 'respond.html', response)

app_jobForum/templates/comments.html
{% extends base %}
{% block content %}
<style type="text/css">
	.job{
		border: 2px solid #003e7e;
		margin:1rem;
		color: #003e7e;
		padding: 2rem;
		display: grid;

	}
	#main-title{
		text-align: center;
		padding: 0;
		color: #003e7e;	
	}
	.photo{
		width: 125px;
		grid-column: 1;
	}

	.content{
		padding: 2rem;
		word-wrap: break-word;
	}
	.form{
		margin-left: 2rem;
		text-align: center;
	}
</style>
<div class="job">
    <div style="grid-column: 1;"><img src="https://pbs.twimg.com/profile_images/1097896051/SilverSurfer_cut_400x400.jpg" class="photo"></div>
    <div style="grid-column: 2" class="content">
        <div class="title"><b> Silver Surfer Company </b></div>
        <br>
        <div style="w"> {{forum.forum}} </div>
    </div>
</div>

{% if all_comments %}
    {% for data in all_comments %}
    <div class="job">
        <div style="grid-column: 1;"><img src="https://pbs.twimg.com/profile_images/1097896051/SilverSurfer_cut_400x400.jpg" class="photo"></div>
        <div style="grid-column: 2" class="content">
            <div class="title"><b> {{ data.name }} </b></div>
            <br>
            <div style="w">{{ data.comment_content }}</div>
        </div>
    </div>
    {% endfor %}
{% endif %}

<div class="form">
    <h1 id="main-title">Add New Comment</h1>
    <form id="form" method="POST" action="{% url 'jobForum:add_comment' id %}">
	    {% csrf_token %}
	    {{ comment_form }}
	    <br>
	    <div style="margin: 1rem;text-align: center">
	    <input id="submit" class="cd-btn" type="submit" id="btn-purchase" data-wipe="Add New Comment" value="Add New Comment" data-wow-delay="1s"></div>
	    <br>
     </form>
</div>

{% endblock %}

app_jobForum/templates/job_forum.html
{% extends base %}

{% block content %}
<style type="text/css">
	.job{
		border: 2px solid #003e7e;
		margin:1rem;
		color: #003e7e;
		padding: 2rem;
		display: grid;

	}
	#main-title{
		text-align: center;
		padding: 0;
		color: #003e7e;
	}
	.photo{
		width: 125px;
		grid-column: 1;
	}

	.content{
		padding: 2rem;
		word-wrap: break-word;
	}
	.form{
		margin-left: 2rem;
		text-align: center;
	}
</style>
<br>
<h2 id="main-title">Silver Surfer Company Job Forum</h2>
{% if all_forum %}
    {% for data in all_forum %}
		<div class="job">
			<div style="grid-column: 1;"><img src="https://pbs.twimg.com/profile_images/1097896051/SilverSurfer_cut_400x400.jpg" class="photo"></div>
			<div style="grid-column: 2" class="content">
				<div class="title"><b> Silver Surfer Company </b></div>
				<br>
				<div style="w">{{ data.forum }}</div>
				<a href="{% url 'jobForum:comments' data.id %}" class="btn btn-warning"> View Comment </a>
			</div>
		</div>
	 {% endfor %}
{% endif %}

<br>
<div class="form">
    <h1 id="main-title">Add New Forum</h1>
    <form id="form" method="POST" action="{% url 'jobForum:add_forum' %}">
	    {% csrf_token %}
	    {{ forum_form }}
	    <br>
	    <div style="margin: 1rem;text-align: center">
	    <input id="submit" class="cd-btn" type="submit" id="btn-purchase" data-wipe="Add New Forum" value="Add New Forum" data-wow-delay="1s"></div>
	    <br>
     </form>
</div>
<br>

{% endblock %}

app_mainAndLogin/templates/main.html
{% extends base %}
{% load staticfiles %}
{% load static %}


{% block content %}


<style type="text/css">
    .job{
        text-align: left;
        border: 2px solid #003e7e;
        margin:1rem;
        color: #003e7e;
        padding: 2rem;
        display: grid;

    }
</style>

<h2 id="main-title" style="color: #173c77; text-align: center;"><font>Silver Surfer Company Job Forum</font></h2>
{% if all_forum %}
    {% for data in all_forum %}
        <div class="job">
            <div style="grid-column: 1;"><img src="https://pbs.twimg.com/profile_images/1097896051/SilverSurfer_cut_400x400.jpg" class="photo" style="width: 100px;height: 100px;"></div>
            <div style="grid-column: 2" class="content">
                <br>
                <div class="title"><b> Silver Surfer Company </b></div>
                <br>
                <div style="w">{{ data.forum }}</div>
                <a href="{% url 'jobForum:comments' data.id %}" class="btn btn-warning"> View Comment </a>
            </div>
        </div>
     {% endfor %}
{% endif %}

<script type="text/javascript">
    var buatbaru = function(data){
        console.log("buat baru");
        $.ajax({
            method: "POST",
            url: '{% url "mainAndLogin:add_Perusahaan"}',
            data: {data},
            success: function(data){
                id = data['id'];
            },
        });
    };
</script>

{% endblock %}

app_profile/templates/profile.html
{% extends base %}

{% block content %}
<style>
@import url("https://fonts.googleapis.com/css?family=Fjalla+One");
@import url("https://fonts.googleapis.com/css?family=Roboto+Slab");
* {
  box-sizing: border-box;
}

html, body {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
}

.profile {
  width: 1080px;
  left: 50%;
  float: left;
  position: relative;
  margin: 50px 0px 50px 0px;
  margin-left: -540px;
  cursor: pointer;
}

.profile .imageHolder {
  float: left;
  width: 30%;
  position: relative;
  left: 5%;
}

.profile .imageHolder .profilePic {
  width: 100%;
  float: left;
  position: relative;
  -webkit-filter: grayscale(100%);
  filter: grayscale(100%);
  transition: all 0.5s ease;
  -webkit-transition: all 0.5s ease;
  -webkit-box-shadow: 0px 0px 31px -1px #474747;
  -moz-box-shadow: 0px 0px 31px -1px #474747;
  box-shadow: 0px 0px 31px -1px #474747;
}

.profile .imageHolder:after {
  content: '';
  pointer-events: none;
  background-size: 50%;
  background-repeat: no-repeat;
  background-position: center top;
  width: 100%;
  min-height: 30vh;
  display: block;
  top: 4vw;
  opacity: 0;
  float: left;
  position: absolute;
  z-index: 1000;
  left: 0;
  transition: all .5s ease;
  -webkit-transition: all .5s ease;
  animation: bounce .5s linear infinite;
  animation-play-state: paused;
}

.profile h1 {
  font-family: 'Fjalla One', sans-serif;
  color: #D10606;
  position: absolute;
  width: 100%;
  padding: 0px 0px 0px 32%;
  margin-top: -50px;
  margin-bottom: 0px;
  font-size: 15vw;
  letter-spacing: 1vw;
  z-index: 10000;
  font-weight: 400;
  text-transform: uppercase;
  pointer-events: none;
  transition: all .5s ease;
  -webkit-transition: all .5s ease;
}

.profile h1:after {
  content: '';
  float: left;
  position: absolute;
  left: 50%;
  bottom: -10vw;
  width: 5px;
  height: 10vw;
  background-color: #D10606;
}

.profile:hover h1 {
  transform: translateY(30vw);
}

.profile:hover .profilePic {
  -webkit-filter: grayscale(0%);
  filter: grayscale(0%);
  transform: scale(1.1);
}

.profile:hover .imageHolder:after {
  opacity: 1;
  animation-play-state: running;
}

.profile .infoHolder {
  width: 60%;
  float: right;
  right: 1%;
  position: absolute;
  overflow-x: hidden;
}

.profile .infoHolder h2 {
  font-family: 'Fjalla One', sans-serif;
  color: #003e7e;
  letter-spacing: 3px;
  margin-top: 0px;
  float: left;
  width: 100%;
  transform: translateX(102%);
  transition: all .5s ease;
  -webkit-transition: all .5s ease;
}

.profile .infoHolder p {
  font-family: 'Roboto Slab', serif;
  float: left;
  margin-top: 0px;
  width: 100%;
  transform: translateX(102%);
  transition: all .62s ease;
  -webkit-transition: all .62s ease;
}

.profile:hover .infoHolder h2, .profile:hover .infoHolder p {
  transform: translateX(0%);
}

@media screen and (min-width: 1080px) {
  .profile h1 {
    margin-top: 50pt;
    font-size: 100pt !important;
    letter-spacing: 12pt !important;
  }
  .profile h1: after {
    bottom: -120px !important;
    height: 120px !important;
  }
  .profile:hover h1 {
    transform: translateY(320px);
  }
}

@media screen and (max-width: 1080px) {
  .profile {
    width: 100%;
    left: 0%;
    margin-left: 0px;
  }
}

@keyframes bounce {
  0% {
    transform: translateY(0px);
  }
  50% {
    transform: translateY(5px);
  }
  100% {
    transform: translateY(0px);
  }
}

.cta-btn-wrapper{
  padding-bottom: 155vh;
  padding-top: 10vh;
}
</style>

<div class="profile" >
  <div class="imageHolder"><img class="profilePic" src="https://i.imgur.com/9H1imhh.jpg"></div>
</div>
  {% if user %}
  <h1 class="strokeme" id="company_name_kill_me"> {{ user.nama }}</h1>
  <div class="infoHolder">
  <h2>Welcome!</h2>
  
  <p id="company_desc_kill_me">Company Description : {{ user.deskripsi }}</p>
  <p id="company_type_kill_me">Company Type : {{ user.tipe }} </p>
  <p id="company_web_kill_me">Website : {{ user.weburl }}</p>
  <p id="company_specialty_kill_me">Specialties : {{ user.specialties }} </p>

  {% endif %}

  <p>
    <a class="cd-btn main-action" data-wipe="Looking for Student" role="button" data-wow-delay="1s">Looking For Student</a>
    <a href="/job-forum/" class="cd-btn main-action" data-wipe="See Villain Forum" role="button" data-wow-delay="1s">See Villain Forum</a>
  </p>

</div>



<div id="name"></div>
<div id="picture"></div>


{% endblock %}

app_respondToMain/templates/respond.html
{% extends base %}
{% block content %}

{% endblock %}

templates/partials/footer.html
<p class="text-center"><a href="http://mapleleafs.nhl.com/" target="_blank"><img src="https://res.cloudinary.com/dhea7np5x/image/upload/v1459023870/leaf-logo-w_r49wrn.png"></a></p>

templates/partials/header.html
<!-- /// JUMBOTRON \\\ -->
<div class="jumbotron cd-intro">
  <div class="container cd-intro-content mask">
    <div class="hr animated fadeIn">
      <img src="https://res.cloudinary.com/dhea7np5x/image/upload/v1459023870/leaf-logo-w_r49wrn.png" alt="Maple Leaf logo">
      <hr>
    </div>

    <h1 data-content="Ultimate Hockey Pack"><span>Ultimate Hockey Pack</span></h1>

    <div class="action-wrapper">
      <p>
        <a href="#packages" class="cd-btn main-action" role="button">Learn More</a>
        <a href="https://oss.ticketmaster.com/html/home.htmI?team=mapleleafs" class="cd-btn" id="btn-purchase" target="_blank" role="button">Purchase Your Pack</a>
      </p>
    </div>
  </div>
</div>
<!-- /// END JUMBOTRON \\\ -->